"""Create character profiles for a house generated by House_Generator.

The character dictionary has this structure:

    character_name -> [role, current_location, trusts, personality]

``trusts`` is itself a dictionary. It starts empty so every character begins
the story trusting no one.
"""

from House_Generator import generate_house


# Add or remove characters here. Each entry is:
# (character name, role, preferred starting room, personality description)
CHARACTER_DEFINITIONS = [
    (
        "Ignatius Vance",
        "Victim / puzzle magnate",
        "Study",
        "Wealthy, controlling, and secretive.",
    ),
    (
        "Dr. Teddy Marrow",
        "Killer / Vance's personal physician",
        "Bathroom",
        "Calm, clinical, and slightly too helpful; quietly panics when faced with information he cannot safely ask about.",
    ),
    (
        "Wren",
        "Scapegoat #1 / Vance's granddaughter",
        "Bedroom 1",
        "Broke, estranged, and defensive; she appears guilty because she lies about her arrival and was near the crime scene.",
    ),
    (
        "Hettie",
        "Scapegoat #2 / housekeeper",
        "Laundry Room",
        "Loyal, protective, and dutiful; she will tamper with a scene to shield someone she cares about.",
    ),
    (
        "Odette",
        "Civilian (Chaos Agent) / rival game designer",
        "Game Room",
        "Playful, provocative, and mischievous; she enjoys creating confusion and feeding misleading theories.",
    ),
    (
        "Barnaby",
        "Civilian / Vance's old friend",
        "Library",
        "Evasive, anxious, and suspicious-looking by accident; he is desperate to conceal an old financial scandal.",
    ),
    (
        "Colonel Slate",
        "Civilian / head of island security",
        "Mudroom",
        "Procedural, guarded, and a bad liar; disciplined, but protective of her private relationship with Hettie.",
    ),
]


def _starting_location(house: dict[str, list[str]], preferred_room: str) -> str:
    """Return a valid room, using the corridor when a room is unavailable."""
    if preferred_room in house:
        return preferred_room
    return "Corridor"


def build_characters(house: dict[str, list[str]]) -> dict[str, list]:
    """Build the character dictionary for a generated house.

    Args:
        house: The dictionary returned by ``generate_house``.

    Returns:
        A dictionary mapping each character name to a list containing their
        role, starting location, empty trust dictionary, and personality.
    """
    characters: dict[str, list] = {}

    for name, role, preferred_room, personality in CHARACTER_DEFINITIONS:
        characters[name] = [
            role,
            _starting_location(house, preferred_room),
            {},  # No one is trusted at the start.
            personality,
        ]

    return characters


if __name__ == "__main__":
    generated_house = generate_house()
    characters = build_characters(generated_house)

    print("Generated house rooms:")
    print(", ".join(generated_house))

    print("\nCharacters:")
    for name, details in characters.items():
        role, location, trusts, personality = details
        print(
            f"{name}: role={role}, location={location}, "
            f"trusts={trusts}, personality={personality}"
        )
